name: flutter_clean_arch_bloc
packages:
  - core/**
  - features/**


command:
  bootstrap:
    environment:
      sdk: ^3.8.1
      flutter: ">=1.17.0"

    dependencies:
      dio: ^5.9.0
      get_it: ^8.2.0
      injectable: ^2.5.1
      json_annotation: ^4.9.0

    dev_dependencies:
      flutter_lints: ^6.0.0
      build_runner: ^2.8.0
      json_serializable: ^6.11.1
      injectable_generator: ^2.8.1 

scripts:
  clean: melos clean
  cleanAndBootstrap: melos clean && melos bootstrap

  update: flutter pub outdated
  upgrade: flutter pub upgrade --major-versions

  test:
    run: melos exec --concurrency=1 -- flutter test
  
